services:
  - type: web
    name: discord-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    region: oregon
    plan: free
    envVars:
      - key: DISCORD_TOKEN
        sync: false
